### PR TITLE
Docker

### LINKED ISSUE #1452: Docker image on dockerhub/ghcr.io
As referenced in #1340 and #1448 there should be an official docker image from rq on dockerhub (or ghcr.io).

If some official pushs the image to dockerhub, I could create a github workflow for automated pushing of new versions.

### PR DESCRIPTION
**Pull request by rpkak**
Added docker workflow as well as the other changes explained in https://github.com/rq/rq/issues/1452#issuecomment-840546502.

Closes #1452

### CODE REVIEW

**Comment by rpkak** [comment]
I don't think the workflow failture has anything to do with the changed files in the PR

**Comment by rpkak** [comment]
Ok, now with `DOCKER_TOKEN` this PR is ready for review.

**Comment by rpkak** [comment]
Any changes for this PR?

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
