### PR TITLE
Remove `use_connection`

### PR DESCRIPTION
**Pull request by lowercase00**
The deprecation warning for `use_connection` first appeared when the docs moved to this repo (~2019 if I'm not mistaken), this effectively removes the `use_connection` from the codebase. This is also the first step to completely eliminate `local` from the codebase: we are still missing deprecating `push/pop` connections, which are only used by the worker on the `perform_job` method, and the `with Connection` context manager, which already has a deprecation warning in place.

### CODE REVIEW

**Comment by selwin** [comment]
Thanks!

**Comment by gabriels1234** [comment]
@selwin this breaks current django-rq.

**Comment by selwin** [comment]
@gabriels1234 hmm ok, mind taking creating a patch for django-rq? I don't think I'll have the time to look at this in the next few days.

**Comment by gabriels1234** [comment]
@selwin Will try, now focusing on handling #1871

**Comment by gabriels1234** [comment]
@selwin
Does this mean that we should remove also the "get_current_job()"?
this is from django-rq:
image

**Comment by selwin** [comment]
@gabriels1234 yes, we should remove all uses of `use_connection` and use explicit connections instead.

**Comment by ccrvlh** [comment]
@gabriels1234 are you working on the patch? I can help if you need. I think it might be worth to have the version compatibility updated also

**Pull request merged**
