### PR TITLE
Improve the lint situation

### PR DESCRIPTION
**Pull request by y4n9squared**
@selwin Here's some lint fixes (about half fixed) as promised, but there's still some outstanding

```
./tests/test_cli.py:442:121: E501 line too long (138 > 120 characters)
./tests/test_cli.py:647:121: E501 line too long (121 > 120 characters)
./tests/test_cli.py:653:121: E501 line too long (130 > 120 characters)
./tests/test_cli.py:659:121: E501 line too long (134 > 120 characters)
./tests/test_cli.py:683:121: E501 line too long (125 > 120 characters)
./tests/test_cli.py:689:121: E501 line too long (132 > 120 characters)
./tests/test_cli.py:695:121: E501 line too long (130 > 120 characters)
./tests/test_cli.py:701:121: E501 line too long (134 > 120 characters)
./tests/test_cli.py:707:121: E501 line too long (131 > 120 characters)
./tests/test_cli.py:713:121: E501 line too long (135 > 120 characters)
./examples/fib.py:5:26: E226 missing whitespace around arithmetic operator
./examples/fib.py:5:42: E226 missing whitespace around arithmetic operator
./rq/registry.py:44:37: W504 line break after binary operator
./rq/job.py:588:121: E501 line too long (138 > 120 characters)
./rq/worker.py:63:13: E741 ambiguous variable name 'l'
./rq/cli/cli.py:203:121: E501 line too long (144 > 120 characters)
2     E226 missing whitespace around arithmetic operator
12    E501 line too long (144 > 120 characters)
1     E741 ambiguous variable name 'l'
1     W504 line break after binary operator
16
```

and I don't think this will move the needle much unless you guys decide to auto-black the entire code base or something along those lines. Most of the lints are whitespace-related which `black` can handle in one fell swoop.

In the projects that I maintain, we have black + linters (configured to ignore all whitespace checks) registered as pre-commit hooks, which are run in CI as well. 

There's a lot of PR's outstanding though, and doing that might introduce merge conflicts with other contributors, so going to leave this decision up to the maintainers. Feel free to disregard/close this if you think its more disruptive than not.

### CODE REVIEW

**Comment by selwin** [comment]
Thanks! Can we disable `--exit-zero` in the next PR so that incoming PRs would have to pass flake8?

For outstanding PRs, they'd just have to merge their branches with master before being merged in (it doesn't look like the changes in this PR are that extensive).

**Comment by y4n9squared** [comment]
@selwin I was concerned that if we disable `--exit-zero` now, no future PR rebased on master will be mergeable since there are still outstanding lints in the project that do not relate to changes that are incoming.

**Comment by selwin** [comment]
I think there's only one PR that's still being worked on which is https://github.com/rq/rq/pull/1685 . It would be ok if we can fix the remaining lint errors and disable `--exit-zero`.

**Comment by y4n9squared** [comment]
I think it would be best if we fixed the remaining lints by just running `black` on the entire code base and then making sure both `black` and `flake8` pass CI. Seems like #1292 and #1288 could all get knocked out. If you are saying that only one of the 14 outstanding PRs are actually being worked on, the opportunity won't get much better than now :)

**Pull request merged**
