### PR TITLE
Add support for Python 3.7

### LINKED ISSUE #972: "async" function argument causing SyntaxError since Python3.7
In rq/queue.py:

    def __init__(self, name='default', default_timeout=None, connection=None,
                 async=True, job_class=None):
        ...

Python3.7's release note:

    Backwards incompatible syntax changes:

        async and await are now reserved keywords.

### PR DESCRIPTION
**Pull request by jd**
Fixes #972

This is an alternative to #975. I wrote it before seeing it existed (since it did not include a ref to #972).

(I'm not confident that `sync` won't become a keyword some day :)

This also adds Travis test for 3.7, and remove 3.3 and 3.4 as they are not supported anymore in Travis for Xenial.

### CODE REVIEW

**Comment by jd** [comment]
Include 3.7 in Travis

**Comment by jd** [comment]
Fix Travis hopefully

**Comment by jd** [comment]
Pull-request updated, HEAD is now 7a072034e4ca1b125b1f45a064ef2499eb5a4519

**Comment by jd** [comment]
Fix pypy

**Comment by jd** [comment]
Pull-request updated, HEAD is now e3ef59938c59e92e2ffb404ec75a35b8b5e1b2db

**Comment by selwin** [comment]
Decided to go with `is_async` keyword proposed here: https://github.com/rq/rq/pull/977 . Thanks!

**Pull request closed without merging**
