### PR TITLE
Multi Dependency Support [Internal API Changes]

### PR DESCRIPTION
**Pull request by thomasmatecki**
Hi!

After reviewing issues & PRs, it seems dependence upon multiple jobs is not implemented, still on the table, and perhaps even useful to many. If I've misinterpreted, please forgive me :bowing_man: .

In an attempt to make some headway toward _multiple dependence_, I've tried to address https://github.com/rq/rq/pull/1090#issuecomment-497528595.

The intent of this PR is simply to lay groundwork, avoiding any API or functional changes.

For reference: https://github.com/rq/rq/pull/856

### CODE REVIEW

**Comment by thomasmatecki** [comment]
oh my. I have just noticed #279. @selwin @nvie - is this work likely to be reopened? I'm happy to pull on this thread for a bit to try to get in completed (:smiley_cat: though it seems many have attempted this before).

**Comment by selwin** [comment]
This feature is something I'd like to get into RQ, now that RQ's job dependency feature is solid.

This PR looks good, but I think we should create a `_dependency_id` property to keep things backwards compatible for people who use third party packages like django-rq and rq-dashboard.

**Comment by thomasmatecki** [comment]
:+1: @selwin `_dependency_id` added in: d00b6d872ac454b4064f38b0c6debae39472c0ec

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
