### PR TITLE
Black style

### PR DESCRIPTION
**Pull request by aparcar**
This PR applied the black code style, adds it to the CI and README. The changes look big, however no functional changed are applied at all.

The line length is set to [120](https://github.com/rq/rq/pull/1290#discussion_r449855514), which is different from black recommendation of [88](https://github.com/psf/black#command-line-options). I would suggest to stick to the 88 recommendation and adapt the `flake8` check.

### CODE REVIEW

**Comment by selwin** [comment]
> The line length is set to 120, which is different from black recommendation of 88. I would suggest to stick to the 88 recommendation and adapt the flake8 check.

Let's keep it at 120 as most monitors are now wide enough to show 120 characters with no truncation. Forcing some expressions to be split across multiple lines also makes them harder to read in some cases.

I didn't realize black didn't have single/double quote options. This is not a deal breaker, but it's such a shame since single quotes are easier to read. I'm tempted to apply black with `--skip-string-normalization` option.

**Comment by selwin** [comment]
Also, I think we can keep just `redis-py` either one of `3.5.0` and `3.5.3` so the number of tests aren't so large. I think a good compromise for now is to have one minor Redis py version in the matrix and we ignore the patch versions.

**Comment by aparcar** [comment]
> Also, I think we can keep just redis-py either one of 3.5.0 and 3.5.3 so the number of tests aren't so large. I think a good compromise for now is to have one minor Redis py version in the matrix and we ignore the patch versions.

ACK

> I didn't realize black didn't have single/double quote options. This is not a deal breaker, but it's such a shame since single quotes are easier to read. I'm tempted to apply black with --skip-string-normalization option.

I'd recommend the default to stick as close as possible to the *best practises*...

**Comment by aparcar** [comment]
I just rebased this. Is the `'` vs `"` your only concern about this patch?

**Comment by selwin** [comment]
> I just rebased this. Is the ' vs " your only concern about this patch?

Yes. But I'd like to merge https://github.com/rq/rq/pull/1299#issue-447166214 in before getting this PR in so it this doesn't cause merge conflicts.

**Comment by nzjrs** [comment]
FWIW I think these sort of pull requests are more harmful than helpful. They make it harder for everyone that has to maintain out of tree forks for internal or production use cases, and they don't buy that much.

IMO it's more important that a codebase is internally consistent than consistent with some external style.

The amount of work in running a code auto-formatter against a codebase is trivial, so this PR could be recreated at any time

**Comment by aparcar** [comment]
@nzjrs I'm wondering if they can just apply the black style once to their on tree and extract a reformatted patch. The idea of using a code formatter is to make such things easier as well, as you have to adapt to it only once.

> IMO it's more important that a codebase is internally consistent than consistent with some external style.

It is mostly, I guess, but the more people join the less it will be that way. Sure @selwin can focus on that during reviews, but isn't the very idea of auto-formatters to automate that?

> The amount of work in running a code auto-formatter against a codebase is trivial, so this PR could be recreated at any time

That's true, I don't really care when (if ever) this is applied, I just see it as a improvement and therefore created the PR. I can rebase it anytime.

**Comment by selwin** [comment]
I understand both @nzjrs' point as well as having a nice, consistent code base.

If we proceed with this, do I have to run black on my IDE; or does Github have an action that automatically rewrites PRs based on Black rules we defined?

**Comment by aparcar** [comment]
@selwin you'd need to run it each time locally.

**Comment by codyflynnNC** [comment]
@selwin  @aparcar You can configure black to run automatically as a github action(https://github.com/psf/Black/actions/runs/17913292/workflow). You can also configure it run automatically before each commit as a pre-commit hook(https://black.readthedocs.io/en/stable/version_control_integration.html).

**Comment by homeworkprod** [comment]
> > I didn't realize black didn't have single/double quote options. This is not a deal breaker, but it's such a shame since single quotes are easier to read. I'm tempted to apply black with --skip-string-normalization option.
> 
> I'd recommend the default to stick as close as possible to the _best practises_...

Choosing one type of string delimiter over the other is hardly a "best practice".

Being consistent might be. Then again, there are situations when one is more handy than the other, and IMO the idea of Black to just force one kind of style just clashes with that.

After all, they *have* introduced the option to not "normalize" quotes. I use it in every project in which I use Black.

**Comment by aparcar** [comment]
Rebased if that's still of interest.

**Comment by selwin** [comment]
@aparcar if we can keep the single quotes, I'm game :). Thanks for your effort in maintaining this.

**Comment by aparcar** [comment]
@selwin done, to make things pretty you need to run `black -S`

**Comment by aparcar** [comment]
Rebased.

**Comment by lowercase00** [comment]
@aparcar @selwin is this still alive? I do agree that just running `black` would be a great idea a lot easier to make it consistent specially since the codebase does have styling that is not very easy to follow. We do have this and #1288 to close :)

**Comment by aparcar** [comment]
Im happy to rerun the command

**Comment by lowercase00** [comment]
@selwin let us know if there's anything to polish on this (I guess black config is the most relevant thing here).

**Comment by selwin** [comment]
I'm mostly ok with using black. Now the only thing left for me would be to integrate black into my RQ development workflow :)

**Comment by lowercase00** [comment]
If you're on VSCode there's a simple `formatOnSave` that does that automatically.

**Comment by aparcar** [comment]
Updated. I did not format the tests though.

**Comment by aparcar** [comment]
By the way, patches like this seem to be a fine way to sneak in evil code. Please rerun `black` on your local machine and make sure that that you end up with he same diff as I created here :)

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
