### PR TITLE
feat(delayed callbacks - on_success & on_failure)

### PR DESCRIPTION
**Pull request by StepanGavrilov**
Delayed execution for callbacks - on_success & on_failure, like jobs that doesn’t have access to the source code. Different codebases

### CODE REVIEW

**Comment by selwin** [comment]
Hey there, mind explaining the rationale behind this PR?

**Comment by StepanGavrilov** [comment]
I have encountered such a situation that I need to call `on_success` & `on_failure` from different micro-services, that is, I, for example, have:

- Main Service
- Sub service 1
- Sub service 2

I need to call on_success from sub service - 2, but i have job in main service or sub service - 1

**Comment by StepanGavrilov** [comment]
> Hey there, mind explaining the rationale behind this PR?
@selwin 

I have encountered such a situation that I need to call on_success & on_failure from different micro-services, that is, I, for example, have:

Main Service
Sub service 1
Sub service 2
I need to call on_success from sub service - 2, but i have job in main service or sub service - 1

**Comment by selwin** [comment]
Sorry I don't see how this PR addresses that, RQ has no concept of different micro services. If your different micro services are listening to different queues, you can enqueue jobs to those queues or send a success/failure webhook to notify them of success/failures.

**Pull request closed without merging**
