### PR TITLE
Fix some code quality issues

### PR DESCRIPTION
**Pull request by pnijhara**
- Use literal syntax to create the data structure
- Remove unnecessary comprehension
---

Find the other issues found here - [https://deepsource.io/gh/pnijhara/rq/issues/?category=all](https://deepsource.io/gh/pnijhara/rq/issues/?category=all)

This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:

1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/rq/rq).

You can also look at the [docs](https://deepsource.io/docs/guides/quickstart.html) for more details. Do let me know if I can be of any help!

### CODE REVIEW

**Comment by selwin** [comment]
Thanks for the PR! Could you please remove `.deepsource.toml` from this PR so I can merge this in?

**Comment by pnijhara** [comment]
Hey @selwin, the DeepSource config ensures issues like these don't make it to master, primarily from external contributors. The Python analyzer detects over 520 types of issues categorized as bug-risks, anti-patterns, performance and security. The tool is free to use for open-source and is used by projects like https://github.com/uber/ludwig and https://github.com/slackapi/python-slackclient/

Would you be open to give it a try? :)

**Comment by selwin** [comment]
@pnijhara ok, will try it out. Thanks!

**Comment by pnijhara** [comment]
@selwin Thank you for merging this PR. You can install DeepSource now. Steps are very easy for this. You can simply signup at deepsource and activate the project analysis there.

Visit https://deepsource.io/signup/ for signup process.

**Pull request merged**
