### PR TITLE
Changed Queue param 'async' to 'sync' to be Python 3.7 compatible.

### PR DESCRIPTION
**Pull request by mikob**
Got a start on this one.
#921

### CODE REVIEW

**Comment by Florents-Tselai** [comment]
I'd prefer to have an `async_` which follows the "general" (?) convention of adding an `_` in the end. That's the case for other packages that say have a `class_` variable defined (e.g. SQLAlchemy comes to mind).

Switching to `sync` / `synchronous` would be awkward as the point of having a queue system is to have asynchronous tasks :) 
Just my two cents.

**Comment by selwin** [comment]
@mikob do you mind changing the `synchronous` keyword to `asynchronous`? Sorry about this.

Also, could you please open this PR against [v1.0](https://github.com/rq/rq/tree/v1.0) branch?

Hopefully I'll be able to finish working on https://github.com/rq/rq/tree/failed-job-registry in around a month's time and we'll release 1.0 then.

**Comment by mikob** [comment]
@selwin, would you reconsider "sync"? Here's my thinking:

 "Synchronous" is the root word, and "a-synchronous" is just a negation of that. It's harder to fathom a double negation (eg. "async=false" is a double negative) Hence it makes more sense to go with `sync`, and it's also easier to spell out then `synchronous` and more palatable than the lazy fix `async_` IMO. 

The standard node library goes with "sync" such as with `fs.syncReadFile` since async is the default. In our case here, a job queue, async is also the default.

**Comment by mikob** [comment]
@selwin have you reconsidered using "sync" instead -- as per my reasoning above?

**Comment by selwin** [comment]
I'm really 50/50 on this topic.

Using `asynchronous` would provide an easier upgrade path for existing users. On the other hand, if I were designing this library from scratch on Python 3.7, I'd probably choose to use `sync` for the reason you mentioned; `asynchronous` is a bit tricky to spell for non native English speakers like me.

Let's just keep using `sync` since this will be better for the long term. Could you please reopen this PR against the `v1.0` branch?

**Comment by mikob** [comment]
reopened on `v1.0` branch https://github.com/rq/rq/pull/970

**Pull request closed without merging**
