### PR TITLE
call callbacks and prepare job when running sync

### PR DESCRIPTION
**Pull request by ericman93**

### CODE REVIEW

**Comment by selwin** [comment]
@ericman93 can you write a test to ensure that sync jobs also trigger job callbacks?

**Comment by ericman93** [comment]
@selwin added tests and fixed bug status didn't changed in failure

**Comment by selwin** [comment]
Thanks!

**Comment by ericman93** [comment]
@selwin sure :)
any ETA as to when will it be deployed to pypi?

**Comment by selwin** [comment]
I’ll try to cut a release by this weekend.

**Pull request merged**
