### PR TITLE
FIX: ttl can also have zero value.

### PR DESCRIPTION
**Pull request by shubhamdipt**
BUG: TTL = 0 was getting converted to None.

### CODE REVIEW

**Comment by selwin** [comment]
I'm not sure why anyone would want to set `job.ttl` to 0. This would mean the job expires right away.

**Comment by shubhamdipt** [comment]
In any case, zero should not be converted to None. Either zero should be documented as invalid input or it should stay as zero.

**Comment by selwin** [comment]
I think we should disallow 0 TTL. Could you please modify this PR accordingly? Possibly document this as well. Thanks!

**Comment by shubhamdipt** [comment]
In my opinion, we should still allow it as it covers a use case of cleaning up the job immediately. The value 0 does carry relevance in such cases.

**Comment by selwin** [comment]
I think you're confusing `result_ttl` (how long a job result is stored) with `ttl` (how long a job is valid for).

When workers find a job that has expired, it will be discarded without being executed.

**Pull request closed without merging**
