### PR TITLE
remove dependents jobs on parent job delete

### PR DESCRIPTION
**Pull request by psihonavt**

### CODE REVIEW

**Comment by chaffeqa** [comment]
My hack quick fix solution:

django-rq was blowing up in the admin area in this case, so I forked there (rather than here) and made this:

```python
# remove the dependency association
job.connection.srem(job.dependents_key_for(dependency_id), job.id)
# set this job as failed (for requeing WITHOUT dependency)
# This allows all other jobs dependent on this one to continue
job.set_status(JobStatus.FAILED)
# remove the 'dependency_id' from the jobs attributes
job.connection.hdel(job.key, 'dependency_id')
# refresh the job to without dependency
job.refresh()
# remove job from deferred queue
registry = DeferredJobRegistry(
    job.origin,
    connection=job.connection,
    job_class=job.__class__,
)
registry.remove(job)
# move to failed queue
failed_queue = FailedQueue(connection=job.connection, job_class=job.__class__)
failed_queue.push_job_id(job.id)
```

[Forked fix](https://github.com/sportstech/django-rq/blob/master/django_rq/views.py#L222)

**Comment by selwin** [comment]
I think we should create `job.delete_dependents()` before merging https://github.com/ui/django-rq/pull/237 in. Do you mind creating a PR for this?

**Comment by chaffeqa** [comment]
I agree @selwin unfort I have to say, as much as I appreciate the work you and @nvie and company have done on this, I **wish** i could do more to give back, but im currently working 80 hour weeks on our project and probably will be doing the same until late september at the earliest.

For my own health (ha) I think all I can allow myself to do is post the solutions I've had to come up with as concepts.

Terribly sorry, like I said I wish I had the time to give back to you guys for all the work and wins you have gotten the community + my company, but I just cant right now.  Hopefully down the road as I said

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/916/files

**Pull request closed without merging**
