### PR TITLE
handle Unicode in Job args & kwargs -- patch adapted from 7wonders

### PR DESCRIPTION
**Pull request by ghost**
This patch allows Jobs to have unicode args and kwargs.

Code is derived from 7wonders. I changed it from %-type formatting to str.format, so that args and kwargs could have non-string arguments. (Previously it was raising AttributeError.)   Test added.

This is my first pull request! Let me know if I should do something else.  Cheers!

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@selwin #438 is not the fix, unfortunately I can't reopen this PR.

This PR addresses the unicode issues in ``job.get_call_string()`` highlighted in #405 and pointed out above by @vlinhart 

I tested 2b14d18 above from @alternativshik and that fixed my issue.

Unfortunately I can't reopn the PR.

**Comment by selwin** [comment]
@dwaynebailey Ok, mind creating a new PR with https://github.com/nvie/rq/commit/2b14d18a0d275df0d7bbdc00d54b927659571f10 ? This PR still doesn't pass Python 3 tests if I recall correctly.

**Comment by alternativshik** [comment]
No, it passed all tests https://travis-ci.org/nvie/rq/builds/36220678

**Comment by dwaynebailey** [comment]
@selwin #492 is the new PR, some confusion in that the working code was never PR'd, but now it is.

**Pull request closed without merging**
