### PR TITLE
test: add static application security testing

### PR DESCRIPTION
**Pull request by kuwv**
Howdy @selwin,

This commit adds some security checks to ensure something doesn't slip though and potentially cause havoc later. There are 5x low level vulnerabilities currently. LMK if you want me to silence these or resolve them.

Also, fixed some of the syntax issues with the `pyproject.toml` while I was updating it.

### CODE REVIEW

**Comment by kuwv** [comment]
ping @selwin, I'd like to get this done before January 1st if possible.

**Comment by selwin** [comment]
@kuwv I'm ok with merging this in. Do you mind taking a look at whether you can increase the coverage for this set of changes?

**Comment by selwin** [comment]
I'm closing this PR for now. Please reopen if you're still interested in merging this in. Thanks!

**Comment by selwin** [comment]
I'm closing this PR for now. Please reopen if you're still interested in merging this in. Thanks!

**Pull request closed without merging**
