### PR TITLE
Add the Python dev packages for Python headers to tests/Dockerfile

### PR DESCRIPTION
**Pull request by robhudson**
The Docker tests were failing for me since psutil was trying to compile and looking for Python headers. With the python dev packages added these now work again.

Python 3.6 is skipped during the test runs presumably because the deadsnakes packages no longer build Python 3.6. So this could be removed later as part of an overall update to drop support. I'm leaving it as-is for now.

### CODE REVIEW

**Comment by selwin** [comment]
Let's drop Python 3.6 this release since it's been EOL more than a year ago.

**Comment by robhudson** [comment]
Okay, I removed Python 3.6 from the testing workflows.

**Comment by selwin** [comment]
Thanks!

**Comment by robhudson** [comment]
> Let's drop Python 3.6 this release since it's been EOL more than a year ago.

And Python 3.7 security support [ended 2 days](https://endoflife.date/python) ago (Jun 27) 😱

**Comment by selwin** [comment]
> And Python 3.7 security support [ended 2 days](https://endoflife.date/python) ago (Jun 27) 😱

Yeah, but I'd like to keep 3.7 compatibility for a bit more, as long as it's not high maintenance or there's a good reason to drop it (like packaging support in 3.6).

**Pull request merged**
