### PR TITLE
Allow CA be passed as a variable

### PR DESCRIPTION
**Pull request by elbuo8**
Currently SSL CA can only be passed in via a file in disk. `redis-py` allows passing the value as a string.

### CODE REVIEW

**Comment by elbuo8** [comment]
Weird that linting fails on a fresh work 🤔

**Comment by selwin** [comment]
Do you mind documenting this option?

**Comment by elbuo8** [comment]
@selwin 👍🏽

**Comment by elbuo8** [comment]
@selwin 👋🏽

**Comment by selwin** [comment]
All tests need to pass before I can merge this in

**Comment by elbuo8** [comment]
Could you re-trigger? The failures are not related to the change 🤔

**Comment by selwin** [comment]
Merged, thanks!

**Pull request merged**
