### PR TITLE
Add logging for job retries

### PR DESCRIPTION
**Pull request by duc00**
This PR improves observability of job workflows. 

It is quite painful to easily figure whether a job has been retried or is done retrying, after a failure. Currently not possible via looking at logs. The PR helps with that by logging when the job has been enqueued/scheduled as part of a retry, and with how many retries left.

Hope this helps!

### CODE REVIEW

**Comment by kuwv** [comment]
@duc00 Don't use f-strings for logging. It is potentially a security vulnerability depending on the job content.

**Comment by duc00** [comment]
@kuwv will update.

There are other occurrences of f-strings in this file, thus I just copied what seemed to be the pattern. Should I update those statements too?

Also how can f-strings not be safe in this case?

**Comment by kuwv** [comment]
F-strings are a powerful templating tool that allows scope inspection and code execution.

https://bugs.python.org/issue46200#msg409499

**Comment by selwin** [comment]
@duc00 please update the PR so I can merge this in :)

**Comment by duc00** [comment]
@selwin @kuwv done! 👍

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
