### PR TITLE
Add at_front for scheduled/enqueue_at jobs

### PR DESCRIPTION
**Pull request by gabriels1234**
as per @selwin's request, I'm submitting this small PR to add at_front capabilities to scheduled jobs. This is my first PR to an open-source project, so any guidance would be really appreciated. (Will have similar PR for RQ-Scheduler)

### CODE REVIEW

**Comment by gabriels1234** [comment]
@selwin Did I mention the carbon footprint reduction of this change could be greatly reduced by this PR, (and the infrastructure cost can go down significantly)?

**Comment by selwin** [comment]
I'd love to be a contributor to greatly reducing carbon emissions :). This PR is missing tests though.

**Comment by gabriels1234** [comment]
> I'd love to be a contributor to greatly reducing carbon emissions :). This PR is missing tests though.
@selwin 
Glad to hear that! I've added a test based off the enqueue_at test, and run the test suit to see it pass (or fail if I changed anything). Please let me know if There's a need for more tests, or some angle of testing the code I added was left unexplored.

**Comment by gabriels1234** [comment]
@selwin looking forward to it!

**Comment by selwin** [comment]
Looks good, will merge if all tests pass.

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
