### PR TITLE
feat: avoided "zombie" processes after killing work horse

### PR DESCRIPTION
**Pull request by theambient**
by setting work horse process group and killing the whole group.
might be useful if task runs other subprocesses.

### CODE REVIEW

**Comment by theambient** [comment]
Where can I find out failed test (all tests) logs so that I can find out what failed ? in my local env (mac) all tests are passed (and some of them are skipped)

**Comment by selwin** [comment]
You can see the failing checks here, in this case it’s codecov that breaks. I wouldn’t worry about this one since codecov doesn’t properly track codes run by the work horse.

898900D6-D200-4653-BC40-5D88DBDFAD21

Would it be hard to create a test that simulates a job that creates other subprocesses and check whether all of them are killed along with the horse?

**Comment by theambient** [comment]
@selwin sure, i will make such test

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
