### PR TITLE
Support for multiple job dependencies

### PR DESCRIPTION
**Pull request by selwin**
I started with @jchia's awesome [initial pull request](https://github.com/nvie/rq/pull/277) and reworked some parts to make it more readable (hopefully).

As far as I'm concerned, this PR is mostly complete except for some pipelining that we need to do for efficiency reasons.

Would be great if @nvie and @jchia can do another quick review on this PR so we can get this merged and get 0.4 out the door.

### CODE REVIEW

**Comment by julen** [comment]
Besides the merge conflicts, what's holding this from being merged?

**Comment by olingerc** [comment]
Is tgere something holding this back? I could get rid of a whole module in my application when this is introduced. I offer my help if you need it. 
( in fact this is another shameless bump.)

**Comment by yaghmr** [comment]
What's the status of this ticket? What's holding this from being merged?

**Comment by NewbiZ** [comment]
I'm also very interested in this issue :) Any ETA?

**Pull request closed without merging**
