### PR TITLE
rename SIGRTMIN SIGUSR1

### PR DESCRIPTION
**Pull request by virusandy**
didnt work otherwise on pthonnn 3.6

### CODE REVIEW

**Comment by selwin** [comment]
I’m not sure what problem this solves. I run RQ on Python 3.6 and it seems to work just fine. Could you please elaborate more?

**Comment by virusandy** [comment]
It doesn't work at least on macOS, because of no SIGRTMIN on this OS. After
changing to SIGUSR1 works well.

**Comment by selwin** [comment]
Any reason why you'd want to run `HerokuWorker` on MacOS though?

**Comment by selwin** [comment]
Closing this PR as I don't think it's relevant. Please reopen if you feel differently.

**Pull request closed without merging**
