### PR TITLE
Extend worker shutdown

### PR DESCRIPTION
**Pull request by Chronial**
Implements the approach discussed in #802.

This is only a first draft and does not implement all the extensions discussed in #802. The tests are failing and the new behavior is completely missing tests (and is untested).

Since the `HerokuWorker` already implemented parts of this design, I tried to follow its decisions and be backwards compatible with it, even in cases where I disagreed with its decisions.

### CODE REVIEW

**Comment by selwin** [comment]
Thanks for the PR @Chronial. I think immediately moving the job to `FailedQueue` during hard shutdowns is the right move, would be good if we can have a separate PR for this.

At the moment, this PR introduces a retry mechanism for jobs that are killed during hard shutdowns. I think we should take this one step further so that this mechanism works for all failed job executions (so we don't have different APIs for hard shutdowns and failed job executions).

My proposal is to change the API to `queue.enqueue(job, max_retries=5)`. We can then modify `handle_job_failure()` to check whether job should be retried and requeue accordingly.

**Comment by Chronial** [comment]
But I don't want my jobs that failed because somethings broken to be retried. I have no reason to assume that a job that raised an exception would work if I just try it again, but every reason to assume that a job that got interrupted by a shutdown would work if I would just let it run.

What api would you propose for that?

**Comment by selwin** [comment]
For now, let `Worker` calls `handle_job_failure()` on hard shutdowns, which I think is the right behavior. You can attach custom metadata to your jobs and override `worker.handle_job_failure()` on your custom worker class (you already use a custom `HerokuWorker` class anyway) to check whether your metadata exists and put it back in the queue if necessary.

I think it's worth taking the time to design a coherent retry mechanism that addresses common use cases. The proposed reentrant API feels like it's only trying to address the narrow issue of Heroku killing its process after a grace period.

The latest API I'm thinking of if something like this:
```python
```

**Comment by Chronial** [comment]
Would it not be cleaner to handle retries in something like an exception handler as detailed here https://github.com/nvie/rq/issues/802#issuecomment-301645638?

**Comment by selwin** [comment]
@Chronial yes, you could do it that way too. Do give it a try and let me know if it works :)

**Comment by selwin** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
